# Generated by Django 3.2.4 on 2021-06-28 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0004_rename_comments_inventoryhistory_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date time  on which the object was created', verbose_name='created at')),
                ('number', models.PositiveBigIntegerField()),
                ('owner_name', models.CharField(max_length=255)),
                ('owner_identification', models.CharField(blank=True, max_length=255, null=True)),
                ('owner_address', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('D', 'DRAFT'), ('F', 'FINISHED'), ('C', 'CANCELLED')], default='D', max_length=2)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InvoiceDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date time  on which the object was created', verbose_name='created at')),
                ('quantity', models.PositiveBigIntegerField()),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('product_name', models.CharField(blank=True, max_length=255, null=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.invoice')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.product')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
