# Generated by Django 3.2.4 on 2021-08-15 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_alter_invoicedetail_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicedetail',
            name='product_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
