version: '3'

volumes:
  local_mysql_data: {}
  local_aws_data: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./Dockerfile
    image: inventory_local_django
    depends_on:
      - mysql
    volumes:
      - .:/app
    env_file:
      - ./.envs/.mysql
    ports:
      - "8000:8000"
    command: /entrypoint

  mysql:
    image: mysql/mysql-server:5.6
    ports:
      - "3666:3306"
    restart: always
    env_file:
      - ./.envs/.mysql
      - ./.envs/.django
    volumes:
      - local_mysql_data:/var/lib/mysql
  
  # localstack:
  #   image: localstack/localstack:0.12.16
  #   container_name: 'aws_S3'
  #   environment:
  #     - SERVICES=s3
  #     - DEBUG=1
  #     - DEFAULT_REGION=eu-west-1
  #     - AWS_ACCESS_KEY_ID=test
  #     - AWS_SECRET_ACCESS_KEY=test
  #   ports:
  #     - '4566'
  #   volumes:
  #     - 'local_aws_data:/docker-entrypoint-initaws.d'
  #     - 'local_aws_data:/tmp/localstack'
  
networks:
  default:
    external:
      name: inventory-network
      
