version: '3'

volumes:
  local_mysql_data: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./Dockerfile
    image: inventory_local_django
    depends_on:
      - mysql
    volumes:
      - .:/app
    env_file:
      - ./.envs/.mysql
    ports:
      - "8000:8000"
    command: /entrypoint

  mysql:
    image: mysql/mysql-server:5.6
    ports:
      - "3666:3306"
    restart: always
    env_file:
      - ./.envs/.mysql
    volumes:
      - local_mysql_data:/var/lib/mysql
  
networks:
  default:
    external:
      name: inventory-network
      
