# Generated by Django 3.2.4 on 2021-06-17 01:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventoryhistory',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Inventory histories'},
        ),
        migrations.AlterField(
            model_name='inventoryhistory',
            name='old_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='inventoryhistory',
            name='origin',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='inventoryhistory',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='histories', to='inventory.product'),
        ),
    ]
