# Generated by Django 3.2.4 on 2021-06-17 01:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20210617_0118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryhistory',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_histories', to='inventory.product'),
        ),
    ]
