# Generated by Django 3.2.4 on 2021-06-17 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_inventoryhistory_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventoryhistory',
            old_name='comments',
            new_name='comment',
        ),
    ]
